metadata:
  name: app-of-apps
  namespace: default
project: default
repoURL: 'https://github.com/GoldennDragonn/beder-k8s-hub.git'
path: app-of-apps/applications
targetRevision: HEAD
server: 'https://kubernetes.default.svc'
destinationNamespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      maxDuration: 3m0s
      factor: 2
