apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://github.com/GoldennDragonn/beder-k8s-hub.git'
    path: app-of-apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2


mongodb-sharded:
  enabled: true
  syncWave: 1
# mongo-express:
#   enabled: false
#   syncWave: 2
# grafana:
#   enabled: true
#   syncWave: 3
# kafdrop:
#   enabled: true
#   syncWave: 4
  