apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: app-of-apps
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2

grafana:
  enabled: false
  syncWave: "6"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true

prometheus:
  enabled: false
  syncWave: "5"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true

kafdrop:
  enabled: false
  syncWave: "4"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true

kafka:
  enabled: false
  syncWave: "3"
  syncPolicy:
    enable: false

mongoExpress:
  enabled: true
  syncWave: "2"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true

mongodbSharded:
  enabled: false
  syncWave: "1"
  syncPolicy:
    enable: false

nfs:
  enabled: false
  syncWave: "0"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true


  