apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: app-of-apps
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2

grafana:
  enabled: true
  syncWave: "6"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true
  syncOptions:
      enable: false

prometheus:
  enabled: true
  syncWave: "5"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    enable: true
    options:
      - CreateNamespace=true

      
kafdrop:
  enabled: true
  syncWave: "4"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    enable: false
    

kafka:
  enabled: true
  syncWave: "3"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    enable: true
    options:
      - CreateNamespace=true

mongoExpress:
  enabled: true
  syncWave: "2"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    enable: false

mongodbSharded:
  enabled: true
  syncWave: "1"
  syncPolicy:
    enable: false
  # syncOptions:
  #   enable: true
  #   options:
  #     - CreateNamespace=true

nfs:
  enabled: true
  syncWave: "0"
  syncPolicy:
    enable: true
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    enable: true
    options:
      - CreateNamespace=true


  