apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: default

spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/yakovbwork/beder-k8s.git'
    path: kibana/helm-charts/kibana
    targetRevision: main
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
