apiVersion: v1
kind: ConfigMap
metadata:
    name: mongos-init-bederdb

data:
  initdb.js: |
    use bederdb;
    db.dummy.insertOne({});
    db.createUser({
        user: "bederuser",
        pwd: "bederpassword",
        roles: [
            { role: "readWrite", db: "bederdb" }
        ]
    })