apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: default

spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/yakovbwork/beder-k8s.git'
    path: istiod
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
