apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://github.com/GoldennDragonn/beder-k8s-hub.git'
    path: grafana
    targetRevision: HEAD
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
