---
elasticsearchHosts: "http://elasticsearch-master.observability.svc:9200"


kibanaConfig:
  kibana.yml: |
    elasticsearch.username: "admin"
    elasticsearch.password: "yakov123"

resources:
  requests:
    cpu: "200m"
    memory: "1Gi"
  limits:
    cpu: "400m"
    memory: "2Gi"

ingress:
  enabled: true
  className: "nginx"
  pathtype: Prefix
  annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
          nginx.ingress.kubernetes.io/cors-expose-headers: "x-api-version,x-response-time-ms,Access-Control-Allow-Credentials,Access-Control-Allow-Origin,kbn-xsrf,kbn-version,content-type"
          nginx.ingress.kubernetes.io/cors-allow-origin: "http://93.173.78.215"
          nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kube-stack.beder.co.il
      paths:
        - backend:
              service:
                name: kibana-kibana
                port:
                  number: 5601
        - path: /kibana
