# controller:
#   kind: DaemonSet

service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    enableHttps: true
    type: LoadBalancer