controller:
  # config:
  #   ssl-redirect: "false" # we use `special` port to control ssl redirection
  #   server-snippet: |
  #     listen 8000;
  #     if ( $server_port = 80 ) {
  #        return 308 https://$host$request_uri;
  #     }

  kind: Deployment

  containerPort:
    http: 80
    https: 80
    # special: 8000

  resources:
    limits:
      cpu: 200m
      memory: 180Mi
    requests:
      cpu: 100m
      memory: 90Mi


service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      # service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:126996264672:certificate/0f65e44b-511d-4fad-bed5-5bb9553449a3"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      
    # targetPorts:
    #   http: http
    #   https: http

# metrics:
#     enabled: true
#     serviceMonitor:
#       enabled: true
#       additionalLabels:
#         release: "prometheus"
# podAnnotations:
#   prometheus.io/scrape: "true"
#   prometheus.io/port: "10254"
#   prometheus.io/path: "/metrics"

