apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}

spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: '{{ .Values.repoURL }}'
    path: {{ .Values.source.path }}
    targetRevision: {{ .Values.source.targetRevision }}
  destination:
    server: '{{ .Values.destination.server }}'
    namespace: '{{ .Values.namespace }}'
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
    retry:
      limit: {{ .Values.syncPolicy.retry.limit }}
      backoff:
        duration: {{ .Values.syncPolicy.retry.backoff.duration }}
        maxDuration: {{ .Values.syncPolicy.retry.backoff.maxDuration }}
        factor: {{ .Values.syncPolicy.retry.backoff.factor }}

