{{- if .Values.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: {{ .Values.appNamespace}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.grafana.syncWave }}"
    linkerd.io/inject: enabled
    
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: grafana
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  {{- if .Values.grafana.syncPolicy.enable }}
  syncPolicy:
    automated:
      prune: {{ .Values.grafana.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.grafana.syncPolicy.automated.selfHeal }}
  {{- end }}
{{- end }}