{{- if .Values.kafdrop.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.kafdrop.syncWave }}"

spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: kafdrop/chart
    targetRevision: main
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  {{- if or .Values.kafdrop.syncPolicy.enable true }}
  syncPolicy:
    automated:
      prune: {{ .Values.kafdrop.syncPolicy.automated.prune | default true }}
      selfHeal: {{ .Values.kafdrop.syncPolicy.automated.selfHeal | default true }}
  {{- end }}
    syncOptions:
    - CreateNamespace=true
{{- end }}