apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  project: default
  source:
    repoURL: 'https://github.com/GoldennDragonn/beder-k8s-hub.git'
    path: kafdrop/chart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

