{{- if .Values.mongodbSharded.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-sharded
  namespace: {{ .Values.appNamespace}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.mongodbSharded.syncWave }}"

spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: mongodb-sharded
    targetRevision: main
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.mongodbSharded.namespace }}
  {{- if  .Values.mongodbSharded.syncPolicy.enable }}
  syncPolicy:
    automated:
      prune: {{ .Values.mongodbSharded.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.mongodbSharded.syncPolicy.automated.selfHeal }}
  {{- end }}
{{- end }}