{{- if .Values.mongoExpress.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: {{ .Values.appNamespace}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.mongoExpress.syncWave }}"

spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: mongo-express
    targetRevision: main
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  {{- if or .Values.mongoExpress.syncPolicy.enable false }}
  syncPolicy:
    automated:
      prune: {{ .Values.mongoExpress.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.mongoExpress.syncPolicy.automated.selfHeal }}
  {{- end }}
{{- end }}