{{- if .Values.mongoExpress.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.mongoExpress.syncWave }}"
spec:
  project: default
  source:
    repoURL: 'https://github.com/GoldennDragonn/beder-k8s-hub.git'
    path: mongo-express
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}