{{- if .Values.nfs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: nfs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.nfs.syncWave }}"

spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: nfs-subdir-external-provisioner
    targetRevision: main
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.nfs.namespace }}
  {{- if  .Values.nfs.syncPolicy.enable }}
  syncPolicy:
    automated:
      prune: {{ .Values.nfs.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.nfs.syncPolicy.automated.selfHeal }}
  {{- end }}
{{- end }}