{{- if .Values.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.prometheus.syncWave }}"
    
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yakovbwork/beder-k8s.git'
    path: prometheus
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  {{- if  .Values.prometheus.syncPolicy.enable }}
  syncPolicy:
    automated:
      prune: {{ .Values.prometheus.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.prometheus.syncPolicy.automated.selfHeal }}
  {{- end }}
{{- end }}