apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: default

spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/yakovbwork/beder-k8s.git'
    path: kafka
    targetRevision: main
    helm:
      valueFiles:
        - yakov-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
