deleteTopicEnable: false
autoCreateTopicsEnable: true
replicaCount: 3
resources:
  requests: 
    cpu: 250m
    memory: 1Gi
service:
  type: ClusterIP
persistence:
  enabled: true
  storageClass: ""
zookeeper:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m  
