---
elasticsearchHosts: "http://elasticsearch-master.default.svc:9200"


kibanaConfig:
  kibana.yml: |
    elasticsearch.username: "admin"
    elasticsearch.password: "denisi21"

ingress:
  enabled: false
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
          nginx.ingress.kubernetes.io/cors-expose-headers: "x-api-version,x-response-time-ms,Access-Control-Allow-Credentials,Access-Control-Allow-Origin,kbn-xsrf,kbn-version,content-type"
          nginx.ingress.kubernetes.io/cors-allow-origin: "http://93.173.78.215"
          nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kibana.swas.world
      paths:
        - backend:
              service:
                name: kibana-kibana
                port:
                  number: 5601
        - path: /
